name: Deploy on NAS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image locally on NAS
      run: docker build -t static-site:latest .

    - name: Stop old container if exists
      run: docker stop static-site || true

    - name: Remove old container if exists
      run: docker rm static-site || true

    - name: Run new container
      run: docker run -d --name static-site -p 8002:80 static-site:latest
