name: Deploy multi-site on NAS

on:
  push:
    branches: [ "main" ]

jobs:
  site1:
    name: Deploy Site 1 (site1 folder)
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Build docker image from site1 folder
    - name: Build Site 1 image
      run: docker build -t static-site-1:latest site1/

    - name: Stop old Site 1 container
      run: docker stop site1 || true

    - name: Remove old Site 1 container
      run: docker rm site1 || true

    - name: Run new Site 1 container (port 8002)
      run: docker run -d --name site1 -p 8004:80 static-site-1:latest


  site2:
    name: Deploy Site 2 (site2 folder)
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Build docker image from site2 folder
    - name: Build Site 2 image
      run: docker build -t static-site-2:latest site2/

    - name: Stop old Site 2 container
      run: docker stop site2 || true

    - name: Remove old Site 2 container
      run: docker rm site2 || true

    - name: Run new Site 2 container (port 8003)
      run: docker run -d --name site2 -p 8003:80 static-site-2:latest


  site3:
    name: Deploy Site 3 (Super5)
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Site 3 image
      run: docker build -t static-site-3:latest site3/

    - name: Stop old Site 3 container
      run: docker stop site3 || true

    - name: Remove old Site 3 container
      run: docker rm site3 || true

    - name: Run new Site 3 container (port 8005)
      run: docker run -d --name site3 -p 8005:80 static-site-3:latest
